[[main]]
name = "Blog"
pageRef = "blog"
weight = 10

# [[main]]
# name = "Publications"
# pageRef = "publications"
# weight = 15

# [[main]]
# name = "Resume"
# pageRef = "resume"
# weight = 20


[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"
icon = "search"

# [[footer]]
# name = "GitHub"
# url = "https://github.com/nealfennimore"
# weight = 10
# [footer.params]
# icon = "github"
# showName = false
# target = "_blank"

# [[footer]]
# name = "LinkedIn"
# url = "https://linkedin.com/in/nealfennimore"
# weight = 20
# [footer.params]
# icon = "linkedin"
# showName = false
# target = "_blank"

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 25
