
[author]
name = "Intelligent Microsystems"
image = ""
headline = ""
bio = ""
links = [
    #     { github = "https://github.com/nealfennimore" },
    #     { linkedin = "https://linkedin.com/in/nealfennimore" },
]

[homepage]
layout = "profile"
showRecent = true

[article]
showDateUpdated = true

[footer]
showThemeAttribution = false
